name: first actions hello

on: 
   push:
     branches: 
       - master
   pull_request:
     types: [closed]
     
           

env:
   name: Adjei Marrion 
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       name: Marrion AJ

    steps:
    - name: Run a one-line script
      run: |
        echo Hello $name!
        echo Actor: ${{ github.actor }}
        echo Comitted By:: ${{ github.event.comits[0].author.name }}
  weather:
     runs-on: [ubuntu-latest]
     env:
        location: '5.6037, 0.1870'
        lang: en
        units: us
        exclude: 'minutely,hourly,daily,alerts,flags'
        dark_sky_secret:  ${{ secrets.dark_sky }}
        
     steps:
         - name: Current Weather
           run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret
  dump:
        runs-on: ubuntu-latest
        steps:
           - env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
             run: echo "$GITHUB_CONTEXT"
  
  pull_requests_only:

    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Hi, $name!

